'use client';
import { useEffect } from 'react';

export default function LandingPage() {
  useEffect(() => {
    const topbar = document.getElementById('topbar');
    const flcta = document.getElementById('flcta');
    const btt = document.getElementById('btt');
    const handleScroll = () => {
      if(topbar) topbar.classList.toggle('scrolled', scrollY > 50);
      if(flcta) flcta.classList.toggle('show', scrollY > 600);
      if(btt) btt.classList.toggle('show', scrollY > 800);
    };
    window.addEventListener('scroll', handleScroll);
    const obs = new IntersectionObserver(e => {
      e.forEach((el, i) => { if(el.isIntersecting) { setTimeout(() => el.target.classList.add('vis'), i * 60); obs.unobserve(el.target); } });
    }, { threshold: 0.1, rootMargin: '0px 0px -40px 0px' });
    document.querySelectorAll('.rv,.rv-l,.rv-r,.rv-s').forEach(el => obs.observe(el));
    document.querySelectorAll('a[href^="#"]').forEach(a => {
      a.addEventListener('click', e => { e.preventDefault(); const t = document.querySelector(a.getAttribute('href')); if(t) t.scrollIntoView({ behavior: 'smooth', block: 'start' }); });
    });
    const carousel = document.getElementById('featCarousel');
    let autoScroll;
    if(carousel) {
      const startAuto = () => { autoScroll = setInterval(() => { if(carousel.scrollLeft >= carousel.scrollWidth - carousel.clientWidth - 10) carousel.scrollTo({ left: 0, behavior: 'smooth' }); else carousel.scrollBy({ left: 340, behavior: 'smooth' }); }, 3500); };
      startAuto();
      carousel.addEventListener('mouseenter', () => clearInterval(autoScroll));
      carousel.addEventListener('mouseleave', startAuto);
      carousel.addEventListener('touchstart', () => clearInterval(autoScroll), { passive: true });
    }
    const steps = [
      {emoji:'🏠',title:'Créez votre salon',desc:'Nom, adresse, description, logo. En 2 minutes votre salon existe en ligne.',mock:'<div style="display:flex;gap:8px;margin-top:4px"><div style="width:24px;height:24px;border-radius:6px;background:#1A1A1A"></div><div style="width:24px;height:24px;border-radius:6px;background:#635BFF"></div><div style="width:24px;height:24px;border-radius:6px;background:#EC4899"></div><div style="width:24px;height:24px;border-radius:6px;background:#F59E0B"></div><div style="width:24px;height:24px;border-radius:6px;background:#10B981"></div></div>'},
      {emoji:'✂️',title:'Ajoutez vos prestations',desc:'Coupe, couleur, balayage… Prix, durée, photo. Votre carte comme un menu.',mock:'<div style="display:flex;justify-content:space-between;font-size:11px;padding:6px 0;border-bottom:1px solid #E8E8E4"><span>Balayage</span><span style="font-weight:600">120€ · 2h</span></div><div style="display:flex;justify-content:space-between;font-size:11px;padding:6px 0;border-bottom:1px solid #E8E8E4"><span>Coupe + Brushing</span><span style="font-weight:600">55€ · 45min</span></div><div style="display:flex;justify-content:space-between;font-size:11px;padding:6px 0"><span>Coloration</span><span style="font-weight:600">85€ · 1h30</span></div>'},
      {emoji:'👩‍🎨',title:'Ajoutez votre équipe',desc:'Chaque coiffeuse a sa couleur, ses objectifs, ses commissions.',mock:'<div style="display:flex;gap:10px"><div style="display:flex;align-items:center;gap:6px"><div style="width:10px;height:10px;border-radius:50%;background:#8B5CF6"></div><span style="font-size:10px">Sophie</span></div><div style="display:flex;align-items:center;gap:6px"><div style="width:10px;height:10px;border-radius:50%;background:#06B6D4"></div><span style="font-size:10px">Marie</span></div><div style="display:flex;align-items:center;gap:6px"><div style="width:10px;height:10px;border-radius:50%;background:#EC4899"></div><span style="font-size:10px">Léa</span></div></div>'},
      {emoji:'📋',title:'Importez vos clientes',desc:'Glissez votre fichier Excel ou ajoutez-les une par une.',mock:'<div style="font-size:10px;color:#999;text-align:center;padding:8px;border:2px dashed #E8E8E4;border-radius:8px">📁 Glissez votre fichier Excel ici</div>'},
      {emoji:'🎨',title:'Personnalisez votre page',desc:'Photos, feed, avis. Votre page ressemble à VOTRE salon.',mock:'<div style="display:flex;gap:4px"><div style="flex:1;height:36px;background:#E8E8E4;border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:10px;color:#999">📷</div><div style="flex:1;height:36px;background:#E8E8E4;border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:10px;color:#999">📷</div><div style="flex:1;height:36px;background:#E8E8E4;border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:10px;color:#999">📷</div></div>'},
      {emoji:'💳',title:'Connectez le paiement',desc:'Stripe en 2 clics. Paiement en ligne activé.',mock:'<div style="display:flex;align-items:center;gap:8px"><div style="background:#635BFF;color:#FFF;padding:6px 14px;font-size:10px;font-weight:600;border-radius:4px">Stripe</div><span style="font-size:10px;color:#4ADE80;font-weight:600">✓ Connecté</span></div>'},
      {emoji:'🎉',title:'Partagez votre lien !',desc:"C\'est prêt ! mypresty.com/votresalon",mock:'<div style="text-align:center;font-size:12px;font-weight:500;padding:10px;background:#1A1A1A;color:#FFF;border-radius:6px">mypresty.com/votresalon</div>',confetti:true}
    ];
    let cur = 0;
    function renderStep(i) {
      const s = steps[i], el = document.getElementById('obC');
      if(!el) return;
      el.style.opacity = 0; el.style.transform = 'translateX(10px)';
      setTimeout(() => { el.innerHTML = '<span class="eb">' + s.emoji + '</span><h4>' + s.title + '</h4><p>' + s.desc + '</p>' + (s.mock ? '<div class="mk">' + s.mock + '</div>' : ''); el.style.opacity = 1; el.style.transform = 'translateX(0)'; }, 200);
      document.querySelectorAll('.obdw').forEach((d, j) => { d.classList.toggle('active', j === i); const dot = d.querySelector('.obd'); if(dot) { dot.classList.toggle('active', j === i); dot.classList.toggle('done', j < i); dot.textContent = j < i ? '✓' : j + 1; } });
      const obF = document.getElementById('obF'); if(obF) obF.style.width = ((i / (steps.length - 1)) * 100) + '%';
      const obCnt = document.getElementById('obCnt'); if(obCnt) obCnt.textContent = (i + 1) + ' / ' + steps.length;
      const obPB = document.getElementById('obPB'); if(obPB) obPB.style.visibility = i === 0 ? 'hidden' : 'visible';
      const obNB = document.getElementById('obNB'); if(obNB) obNB.textContent = i === steps.length - 1 ? 'Commencer ! 🎉' : 'Suivant →';
      if(s.confetti) { const sc = document.getElementById('obS'); if(sc) { let c = sc.querySelector('.cc'); if(!c) { c = document.createElement('div'); c.className = 'cc'; sc.appendChild(c); } c.innerHTML = ''; const cols = ['#C4A265','#4ADE80','#8B5CF6','#EC4899','#06B6D4','#F59E0B']; for(let x = 0; x < 30; x++) { const cf = document.createElement('div'); cf.className = 'conf'; cf.style.left = Math.random()*100+'%'; cf.style.animationDelay = Math.random()*1+'s'; cf.style.background = cols[Math.floor(Math.random()*cols.length)]; cf.style.borderRadius = Math.random() > .5 ? '50%' : '0'; cf.style.width = (4+Math.random()*6)+'px'; cf.style.height = (4+Math.random()*6)+'px'; c.appendChild(cf); } } }
    }
    window.obGo = function(d) { const n = cur + d; if(n < 0) return; if(n >= steps.length) { window.location.href = '#essai'; return; } cur = n; renderStep(cur); };
    document.querySelectorAll('.obdw').forEach(d => { d.addEventListener('click', () => { cur = parseInt(d.dataset.step); renderStep(cur); }); });
    renderStep(0);
    return () => { window.removeEventListener('scroll', handleScroll); obs.disconnect(); if(autoScroll) clearInterval(autoScroll); };
  }, []);

  return (<>
    <style dangerouslySetInnerHTML={{ __html: `
*{margin:0;padding:0;box-sizing:border-box}:root{--bg:#FAFAF8;--dark:#1A1A1A;--cream:#F5F3EF;--line:#E8E8E4;--muted:#999;--gold:#C4A265;--green:#4ADE80;--red:#EF4444;--purple:#8B5CF6;--blue:#06B6D4;--sf:'Outfit',sans-serif;--ss:'Cormorant Garamond','Georgia',serif}html{scroll-behavior:smooth}body{font-family:var(--sf);background:var(--bg);color:var(--dark);overflow-x:hidden}::selection{background:var(--dark);color:#FFF}.container{max-width:1140px;margin:0 auto;padding:0 24px}section{padding:100px 0}@media(max-width:768px){section{padding:60px 0}.container{padding:0 16px}}
.rv{opacity:0;transform:translateY(30px);transition:all .7s cubic-bezier(.16,1,.3,1)}.rv.vis{opacity:1;transform:translateY(0)}.rv-l{opacity:0;transform:translateX(-40px);transition:all .7s cubic-bezier(.16,1,.3,1)}.rv-l.vis{opacity:1;transform:translateX(0)}.rv-r{opacity:0;transform:translateX(40px);transition:all .7s cubic-bezier(.16,1,.3,1)}.rv-r.vis{opacity:1;transform:translateX(0)}.rv-s{opacity:0;transform:scale(.95);transition:all .6s cubic-bezier(.16,1,.3,1)}.rv-s.vis{opacity:1;transform:scale(1)}
.top-banner{background:var(--dark);padding:8px 0;overflow:hidden;position:fixed;top:0;left:0;right:0;z-index:101;height:34px}.top-banner-track{display:flex;animation:bs 22s linear infinite;width:max-content}.top-banner-item{font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#FFF;white-space:nowrap;padding:0 40px}.top-banner-item span{color:var(--gold);margin-right:6px}@keyframes bs{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}
.topbar{position:fixed;top:34px;left:0;right:0;z-index:100;padding:0 24px;transition:all .4s}.topbar.scrolled{background:rgba(250,250,248,.96);backdrop-filter:blur(20px);border-bottom:1px solid var(--line)}.topbar-inner{max-width:1140px;margin:0 auto;display:flex;justify-content:space-between;align-items:center;height:60px}.logo{font-size:13px;font-weight:600;letter-spacing:4px;color:var(--dark);text-decoration:none;display:flex;align-items:center;gap:10px}.logo-icon{width:30px;height:30px;background:var(--dark);border-radius:8px;display:flex;align-items:center;justify-content:center}.logo-icon span{color:#FFF;font-family:var(--ss);font-size:11px;font-weight:600}.topbar-nav{display:flex;align-items:center;gap:20px}.topbar-nav a{font-size:12px;letter-spacing:1.5px;text-transform:uppercase;color:var(--muted);text-decoration:none;transition:color .3s}.topbar-nav a:hover{color:var(--dark)}.nb{padding:9px 20px;font-family:var(--sf);font-size:11px;font-weight:600;letter-spacing:2px;text-transform:uppercase;text-decoration:none;transition:all .3s;display:inline-block}.nb-login{border:1px solid var(--line);color:var(--dark);background:transparent}.nb-login:hover{border-color:var(--dark)}.nb-cta{background:var(--dark);color:#FFF !important;border:1px solid var(--dark)}.nb-cta:hover{background:#333;color:#FFF !important}@media(max-width:768px){.topbar-nav a:not(.nb){display:none}.topbar-nav{gap:8px}}
.btn{display:inline-block;padding:14px 30px;font-family:var(--sf);font-size:12px;font-weight:600;letter-spacing:2px;text-transform:uppercase;text-decoration:none;transition:all .3s;cursor:pointer;border:none}.btn-d{background:var(--dark);color:#FFF}.btn-d:hover{background:#333;transform:translateY(-1px)}.btn-o{background:transparent;border:1px solid var(--dark);color:var(--dark)}.btn-o:hover{background:var(--dark);color:#FFF}.btn-big{padding:18px 48px;font-size:14px;letter-spacing:2.5px}
.hero{padding:160px 0 100px;text-align:center;position:relative;overflow:hidden}.hero::before{content:'';position:absolute;top:-200px;right:-200px;width:600px;height:600px;background:radial-gradient(circle,rgba(196,162,101,.06),transparent 70%);pointer-events:none}.hero-badge{display:inline-block;padding:6px 16px;border:1px solid var(--line);font-size:11px;letter-spacing:2px;text-transform:uppercase;color:var(--muted);margin-bottom:28px}.hero-badge span{color:var(--green);margin-right:6px}.hero h1{font-family:var(--ss);font-size:clamp(40px,5.5vw,72px);font-weight:300;line-height:1.1;margin:0 auto 24px;max-width:800px}.hero h1 em{font-style:italic;color:var(--gold)}.hero .sub{font-size:17px;color:var(--muted);line-height:1.7;max-width:580px;margin:0 auto 36px}.hero-ctas{display:flex;gap:12px;justify-content:center;flex-wrap:wrap;margin-bottom:48px}.hero-stats{display:flex;gap:40px;justify-content:center}.hero-stat{text-align:center}.hero-stat .num{font-family:var(--ss);font-size:40px;font-weight:300}.hero-stat .lbl{font-size:11px;color:var(--muted);letter-spacing:1.5px;text-transform:uppercase;margin-top:2px}
.marquee{border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:16px 0;overflow:hidden;background:#FFF}.marquee-track{display:flex;animation:mq 30s linear infinite;width:max-content}.marquee-item{font-size:12px;letter-spacing:3px;text-transform:uppercase;color:var(--muted);white-space:nowrap;padding:0 30px}.marquee-item::after{content:'✦';margin-left:30px;color:var(--line)}@keyframes mq{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}
.problem{background:var(--dark);color:#FFF;padding:80px 0}.problem h2{font-family:var(--ss);font-size:clamp(30px,3.5vw,46px);font-weight:300;margin-bottom:12px}.problem>div>p.pd{font-size:16px;opacity:.5;max-width:600px;line-height:1.7;margin-bottom:40px}.pgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:2px}.pc{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.06);padding:28px;transition:all .3s}.pc:hover{background:rgba(255,255,255,.08)}.pc .icon{font-size:22px;margin-bottom:12px}.pc h3{font-size:15px;font-weight:600;margin-bottom:6px}.pc p{font-size:13px;opacity:.4;line-height:1.6}
.sh{text-align:center;margin-bottom:60px}.sh .tag{font-size:11px;letter-spacing:3px;text-transform:uppercase;color:var(--gold);margin-bottom:12px}.sh h2{font-family:var(--ss);font-size:clamp(30px,3.5vw,50px);font-weight:300;margin-bottom:14px}.sh p{font-size:16px;color:var(--muted);max-width:560px;margin:0 auto;line-height:1.7}
.fr{display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:center;margin-bottom:80px}.fr.rev{direction:rtl}.fr.rev>*{direction:ltr}.fm{background:#FFF;border:1px solid var(--line);padding:20px;box-shadow:0 20px 60px rgba(0,0,0,.06)}.fd{display:flex;gap:6px;margin-bottom:14px}.fd span{width:8px;height:8px;border-radius:50%;background:var(--line)}.fd span:first-child{background:var(--red)}.fd span:nth-child(2){background:#FBBF24}.fd span:nth-child(3){background:var(--green)}.ft .tag{font-size:11px;letter-spacing:3px;text-transform:uppercase;color:var(--gold);margin-bottom:10px}.ft h3{font-family:var(--ss);font-size:clamp(26px,2.5vw,36px);font-weight:300;margin-bottom:8px;line-height:1.2}.ft .pain{font-size:14px;color:var(--red);font-weight:500;margin-bottom:14px;padding:10px 14px;background:#FEF2F2;border-left:3px solid var(--red);display:inline-block}.ft p{font-size:15px;color:var(--muted);line-height:1.8;margin-bottom:16px}.fl{list-style:none;display:flex;flex-direction:column;gap:8px}.fl li{font-size:14px;color:#555;padding-left:20px;position:relative;line-height:1.6}.fl li::before{content:'✓';position:absolute;left:0;color:var(--green);font-weight:700}@media(max-width:768px){.fr,.fr.rev{grid-template-columns:1fr;gap:30px;direction:ltr}}
.fvg{display:flex;gap:20px;margin-top:40px;overflow-x:auto;scroll-snap-type:x mandatory;-webkit-overflow-scrolling:touch;padding-bottom:20px;scroll-padding:24px;cursor:grab}.fvg:active{cursor:grabbing}.fvg::-webkit-scrollbar{height:4px}.fvg::-webkit-scrollbar-track{background:var(--line);border-radius:2px}.fvg::-webkit-scrollbar-thumb{background:var(--dark);border-radius:2px}
.fvc{min-width:320px;max-width:320px;background:#FFF;border:1px solid var(--line);scroll-snap-align:start;transition:all .4s;position:relative;overflow:hidden;display:flex;flex-direction:column;flex-shrink:0;aspect-ratio:9/16;border-radius:16px}
.fvc:hover{transform:translateY(-4px);box-shadow:0 16px 48px rgba(0,0,0,.09);z-index:2}
.fvc-head{padding:28px 24px 0;flex-shrink:0}
.fvc-icon{width:56px;height:56px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:26px;margin-bottom:16px}
.fvc-head h4{font-size:20px;font-weight:600;margin-bottom:6px;line-height:1.3}
.fvc-head .fvb{display:inline-block;padding:3px 9px;font-size:9px;letter-spacing:1px;text-transform:uppercase;font-weight:700;border-radius:3px;margin-left:6px;vertical-align:middle}
.fvb-ia{background:#F3E8FF;color:var(--purple)}.fvb-u{background:#FEF3C7;color:#92400E}.fvb-a{background:#DCFCE7;color:#166534}
.fvc-pain{font-size:14px;color:var(--red);font-weight:600;margin-top:8px;line-height:1.5;padding:12px 14px;background:#FEF2F2;border-left:3px solid var(--red);border-radius:0 8px 8px 0}
.fvc-body{padding:20px 24px;flex:1;display:flex;flex-direction:column}
.fvc-body p{font-size:15px;color:#555;line-height:1.75}
.fvc-body .detail{font-size:14px;color:var(--muted);line-height:1.7;margin-top:10px}
.fvc-visual{margin-top:auto;padding:16px;background:var(--cream);border-radius:12px;margin:16px 0 0}
.fvc-visual-mini{display:flex;align-items:center;gap:8px;font-size:12px;color:#555}.fvc-visual-mini .dot{width:8px;height:8px;border-radius:50%;flex-shrink:0}
.fvbar{height:6px;background:var(--line);border-radius:3px;overflow:hidden;margin-top:8px}.fvbf{height:100%;border-radius:3px}
.fvc-foot{padding:16px 24px 24px;border-top:1px solid var(--line);margin-top:auto;flex-shrink:0}
.fvc-foot a{font-size:11px;color:var(--dark);font-weight:600;letter-spacing:1px;text-transform:uppercase;text-decoration:none}
.carousel-nav{display:flex;justify-content:center;gap:12px;margin-top:24px}.carousel-nav button{width:44px;height:44px;border-radius:50%;border:1px solid var(--line);background:#FFF;cursor:pointer;font-size:16px;transition:all .3s;display:flex;align-items:center;justify-content:center}.carousel-nav button:hover{background:var(--dark);color:#FFF;border-color:var(--dark)}
.ib{background:#EFF6FF}.ig{background:#F0FDF4}.ip{background:#F5F3FF}.igo{background:#FFFBEB}.ir{background:#FEF2F2}.ic{background:#ECFEFF}.ipk{background:#FDF2F8}
@media(max-width:768px){.fvc{min-width:280px;max-width:280px}}
.ai{background:var(--cream);color:var(--dark);position:relative;overflow:hidden;padding:120px 0}.ai::before{content:'';position:absolute;top:0;right:0;width:60%;height:100%;background:linear-gradient(135deg,rgba(139,92,246,.04),rgba(6,182,212,.03));pointer-events:none}.aig{display:grid;grid-template-columns:1fr 1fr;gap:80px;align-items:start}.aip{padding:20px 24px;border-left:4px solid var(--red);background:#FEF2F2;margin-bottom:32px;border-radius:0 12px 12px 0}.aip p{font-size:15px;color:#555;line-height:1.7}.aip strong{color:var(--red);font-size:16px}.aic{background:#FFF;border:1px solid var(--line);padding:24px;margin-bottom:14px;transition:all .3s;display:flex;gap:18px;align-items:flex-start;border-radius:12px}.aic:hover{background:#FFF;border-color:var(--purple);transform:translateX(4px);box-shadow:0 8px 30px rgba(139,92,246,.08)}.aici{width:52px;height:52px;border-radius:14px;background:#F3E8FF;display:flex;align-items:center;justify-content:center;font-size:24px;flex-shrink:0}.aic h4{font-size:17px;font-weight:600;margin-bottom:4px;color:var(--dark)}.aicpn{font-size:13px;color:var(--red);font-weight:500;margin-bottom:6px;line-height:1.5}.aic p{font-size:14px;color:var(--muted);line-height:1.7}.aib{font-size:9px;padding:3px 8px;background:#F3E8FF;color:var(--purple);letter-spacing:1px;text-transform:uppercase;margin-left:8px;border-radius:3px}
.ai-chat{background:#FFF;border:1px solid var(--line);border-radius:16px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,.06)}.ai-chat-head{background:var(--dark);color:#FFF;padding:16px 20px;display:flex;align-items:center;gap:10px}.ai-chat-head .ai-dot{width:10px;height:10px;border-radius:50%;background:var(--green);animation:aiPulse 2s ease-in-out infinite}.ai-chat-head p{font-size:12px;font-weight:600;letter-spacing:1px}@keyframes aiPulse{0%,100%{opacity:1}50%{opacity:.4}}.ai-chat-body{padding:20px;display:flex;flex-direction:column;gap:14px}.ai-msg{padding:14px 18px;border-radius:14px;font-size:14px;line-height:1.7;max-width:88%}.ai-msg-user{background:var(--dark);color:#FFF;align-self:flex-end;border-bottom-right-radius:4px}.ai-msg-ai{background:#F5F3FF;color:var(--dark);align-self:flex-start;border-bottom-left-radius:4px;border:1px solid rgba(139,92,246,.12)}.ai-msg-ai .ai-label{font-size:9px;letter-spacing:1.5px;text-transform:uppercase;color:var(--purple);font-weight:700;margin-bottom:6px}.ai-msg-tip{background:#F0FDF4;border:1px solid rgba(74,222,128,.2);border-radius:12px;padding:14px 18px;font-size:13px;line-height:1.7;color:#555}.ai-msg-tip strong{color:var(--dark)}
@media(max-width:768px){.aig{grid-template-columns:1fr;gap:40px}.ai{padding:80px 0}}
.compare{background:#FFF}.cbox{max-width:700px;margin:40px auto 0;text-align:center}.cmp{background:var(--dark);color:#FFF;padding:28px 36px;margin-bottom:16px}.cmp .name{font-size:18px;font-weight:600;letter-spacing:3px;text-transform:uppercase;margin-bottom:4px}.cmp .desc{font-size:14px;opacity:.5}.coth{border:1px solid var(--line);padding:18px 24px;opacity:.45;margin-bottom:24px}.coth .name{font-size:14px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:var(--muted);margin-bottom:2px}.coth .desc{font-size:13px;color:var(--muted)}.cmsg{font-size:16px;color:#555;line-height:1.8;max-width:600px;margin:0 auto}.cmsg strong{color:var(--dark)}
.onboard{background:var(--cream);overflow:hidden}.obc{position:relative;max-width:700px;margin:40px auto 0}.obp{display:flex;gap:0;margin-bottom:30px;position:relative}.obp::before{content:'';position:absolute;top:50%;left:0;right:0;height:2px;background:var(--line);z-index:0}.obpf{position:absolute;top:50%;left:0;height:2px;background:var(--dark);z-index:1;transition:width .5s cubic-bezier(.16,1,.3,1)}.obd{width:32px;height:32px;border-radius:50%;background:#FFF;border:2px solid var(--line);display:flex;align-items:center;justify-content:center;font-family:var(--ss);font-size:14px;cursor:pointer;position:relative;z-index:2;transition:all .3s}.obd.active{background:var(--dark);color:#FFF;border-color:var(--dark);transform:scale(1.15)}.obd.done{background:var(--green);border-color:var(--green);color:#FFF}.obdw{flex:1;text-align:center}.obdl{font-size:9px;letter-spacing:1px;text-transform:uppercase;color:var(--muted);margin-top:8px;transition:color .3s}.obdw.active .obdl{color:var(--dark);font-weight:600}.obs{background:#FFF;border:1px solid var(--line);padding:36px;min-height:220px;transition:all .4s;position:relative;overflow:hidden}.obsi{transition:all .4s}.obs .eb{font-size:40px;margin-bottom:16px;display:block}.obs h4{font-family:var(--ss);font-size:24px;font-weight:300;margin-bottom:8px}.obs p{font-size:13px;color:var(--muted);line-height:1.7;max-width:500px}.obs .mk{margin-top:16px;padding:14px;background:var(--cream);border-radius:8px}.obn{display:flex;justify-content:space-between;align-items:center;margin-top:16px}.obn button{padding:10px 24px;font-family:var(--sf);font-size:10px;font-weight:600;letter-spacing:2px;text-transform:uppercase;cursor:pointer;transition:all .3s}.obpb{background:transparent;border:1px solid var(--line);color:var(--muted)}.obpb:hover{border-color:var(--dark);color:var(--dark)}.obnb{background:var(--dark);color:#FFF;border:none}.obnb:hover{background:#333}.obcnt{font-size:11px;color:var(--muted);letter-spacing:1px}.cc{position:absolute;top:0;left:0;right:0;bottom:0;pointer-events:none;overflow:hidden}.conf{position:absolute;width:8px;height:8px;top:-10px;animation:cf 2s ease-in forwards}@keyframes cf{0%{transform:translateY(0) rotate(0);opacity:1}100%{transform:translateY(300px) rotate(720deg);opacity:0}}
.pricing{background:var(--cream)}.pgr{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:2px;margin-top:40px}.pcd{background:#FFF;border:1px solid var(--line);padding:36px 28px;transition:all .3s}.pcd.ft{background:var(--dark);color:#FFF;border-color:var(--dark)}.pcd .tier{font-size:11px;letter-spacing:3px;text-transform:uppercase;color:var(--muted);margin-bottom:6px}.pcd.ft .tier{color:rgba(255,255,255,.4)}.pcd h3{font-family:var(--ss);font-size:30px;font-weight:300;margin-bottom:4px}.pcd .price{font-size:40px;font-weight:200;margin:16px 0 4px}.pcd .price span{font-size:15px;color:var(--muted)}.pcd.ft .price span{color:rgba(255,255,255,.4)}.pcd .billing{font-size:13px;color:var(--muted);margin-bottom:20px}.pcd.ft .billing{color:rgba(255,255,255,.4)}.pcd ul{list-style:none;margin-bottom:24px}.pcd ul li{font-size:14px;padding:7px 0;border-bottom:1px solid var(--line);color:#555}.pcd.ft ul li{border-color:rgba(255,255,255,.08);color:rgba(255,255,255,.7)}.pcd ul li::before{content:'✦ ';color:var(--gold)}.pcd .btn{width:100%;text-align:center;padding:14px}.pcd.ft .btn{background:#FFF;color:var(--dark)}
.tg{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px;margin-top:40px}.tc{background:#FFF;border:1px solid var(--line);padding:28px}.tc .stars{color:var(--gold);font-size:16px;margin-bottom:10px;letter-spacing:2px}.tc blockquote{font-family:var(--ss);font-size:19px;font-style:italic;font-weight:300;line-height:1.6;margin-bottom:16px;color:#333}.tc .author{font-size:12px;letter-spacing:1px;text-transform:uppercase;color:var(--muted)}
.fcta{background:#FFF;color:var(--dark);text-align:center;padding:100px 0;border-top:1px solid var(--line)}.fcta h2{font-family:var(--ss);font-size:clamp(36px,4.5vw,60px);font-weight:300;margin-bottom:16px;line-height:1.1}.fcta h2 em{font-style:italic;color:var(--gold)}.fcta>p{font-size:16px;color:var(--muted);max-width:500px;margin:0 auto 36px;line-height:1.7}.fcta .trial{font-size:13px;color:var(--muted);margin-top:20px;letter-spacing:1px}
footer{padding:40px 0;border-top:1px solid var(--line);background:var(--bg)}.fi{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:16px}.fb{font-size:11px;letter-spacing:3px;font-weight:600}.flinks{display:flex;gap:24px}.flinks a{font-size:10px;color:var(--muted);text-decoration:none;letter-spacing:1px;text-transform:uppercase}.fc{font-size:10px;color:var(--muted)}
.btt{position:fixed;bottom:28px;right:28px;z-index:99;width:48px;height:48px;background:var(--dark);color:#FFF;border:none;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:18px;opacity:0;transform:translateY(20px);transition:all .4s;pointer-events:none;box-shadow:0 4px 20px rgba(0,0,0,.15)}.btt.show{opacity:1;transform:translateY(0);pointer-events:auto}.btt:hover{background:#333;transform:translateY(-2px)}
.flcta{position:fixed;bottom:28px;left:28px;z-index:99;opacity:0;transform:translateY(20px);transition:all .4s;pointer-events:none}.flcta.show{opacity:1;transform:translateY(0);pointer-events:auto}.flcta a{display:flex;align-items:center;gap:8px;padding:14px 24px;background:var(--dark);color:#FFF;text-decoration:none;font-size:11px;font-weight:600;letter-spacing:1.5px;text-transform:uppercase;box-shadow:0 8px 32px rgba(0,0,0,.2)}.flcta a:hover{background:#333}
.mn{display:flex;align-items:center;gap:10px;padding:8px 0;border-bottom:1px solid var(--line);font-size:11px;color:#555}.mn .dot{width:6px;height:6px;border-radius:50%;flex-shrink:0}.msr{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--line);font-size:11px}.msr .val{font-weight:600}.mcal{display:grid;grid-template-columns:repeat(5,1fr);gap:4px}.mcal .slot{height:24px;border-radius:3px;font-size:8px;display:flex;align-items:center;justify-content:center;color:#FFF;font-weight:500}.sr{width:120px;height:120px;border-radius:50%;background:conic-gradient(var(--green) 0% 78%,var(--line) 78% 100%);display:flex;align-items:center;justify-content:center;margin:0 auto}.si{width:96px;height:96px;border-radius:50%;background:#FFF;display:flex;flex-direction:column;align-items:center;justify-content:center}.si .n{font-family:var(--ss);font-size:32px;font-weight:300;line-height:1}.si .l{font-size:8px;letter-spacing:1px;text-transform:uppercase;color:var(--muted);margin-top:2px}
    `}} />
    <div dangerouslySetInnerHTML={{ __html: `
<div class="top-banner"><div class="top-banner-track"><span class="top-banner-item"><span>✦</span> Essai gratuit 90 jours</span><span class="top-banner-item"><span>✦</span> 42 fonctionnalités</span><span class="top-banner-item"><span>✦</span> 19€/mois sans engagement</span><span class="top-banner-item"><span>✦</span> 0% commission</span><span class="top-banner-item"><span>✦</span> IA prédictive</span><span class="top-banner-item"><span>✦</span> Essai gratuit 90 jours</span><span class="top-banner-item"><span>✦</span> 42 fonctionnalités</span><span class="top-banner-item"><span>✦</span> 19€/mois sans engagement</span><span class="top-banner-item"><span>✦</span> 0% commission</span><span class="top-banner-item"><span>✦</span> IA prédictive</span></div></div>
<div class="topbar" id="topbar"><div class="topbar-inner"><a href="#" class="logo"><div class="logo-icon"><span>MP</span></div>MY PRESTY</a><nav class="topbar-nav"><a href="#fonctionnalites">Fonctionnalités</a><a href="#ia">IA</a><a href="#tarifs">Tarifs</a><a href="/connexion" class="nb nb-login">Se connecter</a><a href="#essai" class="nb nb-cta">Essai gratuit</a></nav></div></div>

<section class="hero" id="top"><div class="container"><div class="hero-badge rv"><span>●</span> Essai gratuit 90 jours — Sans engagement</div><h1 class="rv">Votre salon mérite<br/>mieux qu'un <em>agenda</em></h1><p class="sub rv">MY PRESTY remplace votre agenda papier, votre caisse, votre logiciel de fidélité, vos rappels manuels et vos fichiers Excel. En un seul outil intelligent.</p><div class="hero-ctas rv"><a href="#essai" class="btn btn-d">Créer mon salon gratuitement</a><a href="#fonctionnalites" class="btn btn-o">Voir les fonctionnalités</a></div><div class="hero-stats rv"><div class="hero-stat"><div class="num">42+</div><div class="lbl">Fonctionnalités</div></div><div class="hero-stat"><div class="num">90j</div><div class="lbl">Essai gratuit</div></div><div class="hero-stat"><div class="num">19€</div><div class="lbl">Par mois</div></div></div></div></section>

<div class="marquee"><div class="marquee-track"><span class="marquee-item">Agenda intelligent</span><span class="marquee-item">Caisse intégrée</span><span class="marquee-item">IA prédictive</span><span class="marquee-item">Avis automatiques</span><span class="marquee-item">QR Code</span><span class="marquee-item">Fidélité gamifiée</span><span class="marquee-item">Rappels intelligents</span><span class="marquee-item">Multi-salon</span><span class="marquee-item">Score de santé</span><span class="marquee-item">Factures auto</span><span class="marquee-item">Agenda intelligent</span><span class="marquee-item">Caisse intégrée</span><span class="marquee-item">IA prédictive</span><span class="marquee-item">Avis automatiques</span><span class="marquee-item">QR Code</span><span class="marquee-item">Fidélité gamifiée</span><span class="marquee-item">Rappels intelligents</span><span class="marquee-item">Multi-salon</span><span class="marquee-item">Score de santé</span><span class="marquee-item">Factures auto</span></div></div>

<section class="problem"><div class="container"><h2 class="rv">Aujourd'hui, vous jonglez entre 5 outils</h2><p class="pd rv">Agenda papier, logiciel de caisse, fichier Excel, rappels manuels, carte de fidélité en carton… My Presty les remplace tous.</p><div class="pgrid"><div class="pc rv"><div class="icon">📅</div><h3>L'agenda papier</h3><p>Des ratures, des créneaux perdus, zéro visibilité à distance.</p></div><div class="pc rv"><div class="icon">💰</div><h3>Le logiciel de caisse</h3><p>39€/mois juste pour faire un Z de caisse.</p></div><div class="pc rv"><div class="icon">📊</div><h3>Les fichiers Excel</h3><p>Jamais à jour, personne ne s'en sert.</p></div><div class="pc rv"><div class="icon">📱</div><h3>Les rappels manuels</h3><p>SMS un par un. Oubli = no-show à 80€.</p></div><div class="pc rv"><div class="icon">⭐</div><h3>Les avis Google</h3><p>"Laisse un avis" × 10/jour. Taux : quasi nul.</p></div><div class="pc rv"><div class="icon">🎯</div><h3>La fidélisation</h3><p>Cartes tampons perdues. Aucune idée de qui part.</p></div></div></div></section>

<!-- ═══ BIG SHOWCASES ═══ -->
<section id="fonctionnalites"><div class="container"><div class="sh rv"><p class="tag">Fonctionnalités</p><h2>Tout ce dont votre salon a besoin.<br/>Rien de superflu.</h2><p>Chaque fonctionnalité résout un problème réel que vous vivez au quotidien.</p></div>

<div class="fr"><div class="fm rv-l"><div class="fd"><span></span><span></span><span></span></div><div style="display:flex;gap:8px;margin-bottom:10px"><div style="font-size:9px;letter-spacing:1px;text-transform:uppercase;color:var(--muted);padding:6px 10px;border-bottom:2px solid var(--dark);font-weight:600">Lundi 10</div><div style="font-size:9px;letter-spacing:1px;text-transform:uppercase;color:var(--muted);padding:6px 10px">Mardi 11</div><div style="font-size:9px;letter-spacing:1px;text-transform:uppercase;color:var(--muted);padding:6px 10px">Mer. 12</div></div><div class="mcal"><div class="slot" style="background:#8B5CF6;grid-row:span 2">Balayage<br/>Sarah</div><div class="slot" style="background:var(--dark)">Coupe</div><div class="slot" style="background:#06B6D4;grid-row:span 2">Lissage<br/>Emma</div><div class="slot" style="background:var(--line);color:#999">Libre</div><div class="slot" style="background:var(--gold)">Soin</div><div class="slot" style="background:#EC4899;grid-row:span 2">Couleur<br/>Julie</div><div class="slot" style="background:var(--dark)">Coupe</div><div class="slot" style="background:var(--line);color:#999">Libre</div><div class="slot" style="background:#10B981">Mèches</div></div></div><div class="ft rv-r"><p class="tag">Agenda</p><h3>Un vrai planning visuel, pas une simple liste</h3><div class="pain">😤 "Je vois pas qui est dispo, je dois appeler pour chaque créneau"</div><p>Créneaux en colonnes par coiffeuse, blocs colorés par prestation. Votre planning est enfin lisible en un coup d'œil.</p><ul class="fl"><li>Vue jour, semaine, mois</li><li>Colonnes par membre</li><li>Créneaux auto-générés</li><li>Drag & drop</li></ul></div></div>

<div class="fr rev"><div class="fm rv-r"><div class="fd"><span></span><span></span><span></span></div><div style="text-align:center;padding:16px 0 12px"><p style="font-size:9px;letter-spacing:2px;text-transform:uppercase;color:var(--muted);margin-bottom:4px">Aujourd'hui</p><p style="font-family:var(--ss);font-size:42px;font-weight:300">420€</p></div><div style="display:flex;gap:8px;margin-bottom:16px"><div style="flex:1;background:var(--cream);padding:10px;text-align:center"><p style="font-size:8px;letter-spacing:1px;text-transform:uppercase;color:var(--muted)">CB</p><p style="font-size:16px;font-weight:500">340€</p></div><div style="flex:1;background:var(--cream);padding:10px;text-align:center"><p style="font-size:8px;letter-spacing:1px;text-transform:uppercase;color:var(--muted)">Espèces</p><p style="font-size:16px;font-weight:500">80€</p></div></div><div class="msr"><span>Balayage — Sarah M.</span><span class="val" style="color:var(--green)">+120€</span></div><div class="msr"><span>Coupe — Julie</span><span class="val" style="color:var(--green)">+55€</span></div><div class="msr"><span>Coloration — Emma</span><span class="val" style="color:var(--green)">+165€</span></div></div><div class="ft rv-l"><p class="tag">Caisse</p><h3>Votre comptable va vous adorer</h3><div class="pain">😤 "Ma comptable me réclame un export tous les mois et je galère"</div><p>Journal de caisse complet. CB, espèces, virements. Export CSV et PDF en 1 clic.</p><ul class="fl"><li>Suivi CB / espèces / virement</li><li>Export comptable CSV + PDF</li><li>Factures auto post-RDV</li><li>Remplace votre caisse à 39€/mois</li></ul></div></div>

<div class="fr"><div class="fm rv-l"><div class="fd"><span></span><span></span><span></span></div><div style="display:flex;align-items:center;justify-content:space-between;padding:0 0 12px;border-bottom:1px solid var(--line);margin-bottom:4px"><span style="font-size:12px;font-weight:600">🔔 Notifications</span><span style="background:var(--red);color:#FFF;font-size:9px;font-weight:700;padding:2px 7px;border-radius:10px">5</span></div><div class="mn"><div class="dot" style="background:var(--green)"></div>Sarah Martin — <strong>Balayage</strong> samedi 14h</div><div class="mn"><div class="dot" style="background:var(--gold)"></div>Nouvel avis ⭐⭐⭐⭐⭐ de Julie</div><div class="mn"><div class="dot" style="background:var(--red)"></div>⚠️ Stock Olaplex — 3 restants</div><div class="mn"><div class="dot" style="background:var(--red)"></div>🔴 Emma absente depuis 7 semaines</div><div class="mn" style="border:none"><div class="dot" style="background:var(--purple)"></div>🎉 Objectif de Sophie atteint !</div></div><div class="ft rv-r"><p class="tag">Notifications</p><h3>Ouvrez My Presty comme Instagram</h3><div class="pain">😤 "Je rate des réservations parce que je vérifie pas assez"</div><p>Tout ce qui se passe dans votre salon, en temps réel dans votre clochette.</p><ul class="fl"><li>Réservations en temps réel</li><li>Alertes stock produits</li><li>Clientes en danger</li><li>Objectifs d'équipe</li></ul></div></div>

<div class="fr rev"><div class="fm rv-r" style="text-align:center;padding:30px 20px"><div class="fd" style="justify-content:center"><span></span><span></span><span></span></div><p style="font-size:9px;letter-spacing:2px;text-transform:uppercase;color:var(--muted);margin-bottom:16px">Score de santé</p><div class="sr"><div class="si"><div class="n">78</div><div class="l">/ 100</div></div></div><p style="font-size:12px;color:var(--green);font-weight:600;margin-top:16px">● Bonne santé</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:16px;text-align:center"><div style="background:var(--cream);padding:8px"><p style="font-size:8px;color:var(--muted);letter-spacing:1px;text-transform:uppercase">Remplissage</p><p style="font-size:14px;font-weight:500">82%</p></div><div style="background:var(--cream);padding:8px"><p style="font-size:8px;color:var(--muted);letter-spacing:1px;text-transform:uppercase">Rétention</p><p style="font-size:14px;font-weight:500">91%</p></div><div style="background:var(--cream);padding:8px"><p style="font-size:8px;color:var(--muted);letter-spacing:1px;text-transform:uppercase">Note</p><p style="font-size:14px;font-weight:500">4.8⭐</p></div><div style="background:var(--cream);padding:8px"><p style="font-size:8px;color:var(--muted);letter-spacing:1px;text-transform:uppercase">Croissance</p><p style="font-size:14px;font-weight:500;color:var(--green)">+12%</p></div></div></div><div class="ft rv-l"><p class="tag">Score de santé</p><h3>UN chiffre qui résume tout</h3><div class="pain">😤 "J'ai plein de chiffres mais je sais jamais si ça va bien"</div><p>Remplissage, rétention, avis, CA, annulations, croissance. Tout en un score 0-100 avec des recommandations.</p><ul class="fl"><li>Score en temps réel</li><li>Recommandations hebdo</li><li>Business coach automatique</li></ul></div></div>

</div></section>

<!-- ═══ 42 FEATURES CAROUSEL ═══ -->
<section style="background:var(--cream)" id="tout"><div class="container"><div class="sh rv"><p class="tag">Tout-en-un</p><h2>42 fonctionnalités. 0 compromis.</h2><p>Faites défiler pour découvrir chaque fonctionnalité →</p></div></div>
<div class="fvg rv" id="featCarousel" style="padding-left:max(24px,calc((100vw - 1140px)/2 + 24px))">

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ib">📅</div><h4>Agenda visuel</h4><div class="fvc-pain">😤 "Mon agenda papier est illisible, je vois pas qui est dispo"</div></div><div class="fvc-body"><p>Planning en colonnes par coiffeuse avec blocs colorés par prestation. Vue jour, semaine ou mois.</p><p class="detail">Drag & drop pour déplacer un RDV, créneaux auto-générés selon vos horaires, synchronisation avec Google Calendar.</p><div class="fvc-visual"><div style="display:flex;gap:4px"><div style="flex:1;height:22px;background:#8B5CF6;border-radius:4px"></div><div style="flex:1;height:22px;background:#06B6D4;border-radius:4px"></div><div style="flex:1;height:22px;background:var(--dark);border-radius:4px"></div></div><div style="display:flex;gap:4px;margin-top:4px"><div style="flex:2;height:22px;background:#EC4899;border-radius:4px"></div><div style="flex:1;height:22px;background:var(--line);border-radius:4px"></div></div></div></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ig">💵</div><h4>Caisse intégrée</h4><div class="fvc-pain">😤 "Je paie 39€/mois juste pour un logiciel de caisse à côté"</div></div><div class="fvc-body"><p>Journal de caisse complet : CB, espèces, virements. Totaux en temps réel par mode de paiement.</p><p class="detail">Export CSV et PDF mensuel pour votre comptable. Factures auto après chaque RDV. Remplace votre logiciel de caisse.</p><div class="fvc-visual"><div style="display:flex;justify-content:space-between;font-size:13px"><span style="color:var(--muted)">Aujourd'hui</span><span style="font-weight:700;font-size:18px">420€</span></div><div class="fvbar" style="margin-top:10px"><div class="fvbf" style="width:72%;background:var(--green)"></div></div><p style="font-size:10px;color:var(--muted);margin-top:6px">CB 340€ · Espèces 80€</p></div></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ip">📊</div><h4>Rapport mensuel <span class="fvb fvb-a">Auto</span></h4><div class="fvc-pain">😤 "Je passe des heures à compiler mes chiffres du mois"</div></div><div class="fvc-body"><p>Le 1er du mois, vous recevez un PDF brandé avec CA, top prestations, top clientes, remplissage, note moyenne.</p><p class="detail">Comparaison avec le mois précédent, tendances, recommandations. Envoyé automatiquement par email.</p><div class="fvc-visual"><div style="text-align:center;padding:8px"><p style="font-size:10px;color:var(--muted)">📄 Rapport Mars 2025</p><p style="font-size:20px;font-weight:600;margin-top:4px">8 420€</p><p style="font-size:11px;color:var(--green);font-weight:600;margin-top:2px">+12% vs février</p></div></div></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ir">🔔</div><h4>Notifications push</h4><div class="fvc-pain">😤 "Je rate des réservations parce que je vérifie pas assez souvent"</div></div><div class="fvc-body"><p>Tout ce qui se passe dans votre salon, en temps réel. Réservations, avis, alertes stock, clientes en danger.</p><p class="detail">Ouvrez My Presty comme vous ouvrez Instagram — la clochette vous dit tout. Objectifs atteints, rappels, no-shows signalés.</p><div class="fvc-visual"><div class="fvc-visual-mini"><div class="dot" style="background:var(--green)"></div>Nouvelle résa — Sarah, sam. 14h</div><div class="fvc-visual-mini" style="margin-top:6px"><div class="dot" style="background:var(--red)"></div>⚠️ Stock Olaplex — 3 restants</div></div></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ic">📱</div><h4>QR Code trackable <span class="fvb fvb-u">Unique</span></h4><div class="fvc-pain">😤 "Mes clientes disent qu'elles savent pas comment réserver"</div></div><div class="fvc-body"><p>QR code unique sur comptoir, vitrine, cartes de visite. La cliente scanne → page de réservation directe.</p><p class="detail">Compteur de scans intégré pour mesurer l'impact. Différents QR pour différentes sources (carte, Insta, comptoir).</p><div class="fvc-visual"><div style="text-align:center;padding:6px"><p style="font-size:28px">▦</p><p style="font-size:13px;font-weight:600;margin-top:4px">47 scans ce mois</p></div></div></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon igo">⭐</div><h4>Avis automatiques <span class="fvb fvb-a">Auto</span></h4><div class="fvc-pain">😤 "Je supplie mes clientes de laisser un avis Google, personne ne le fait"</div></div><div class="fvc-body"><p>24h après le RDV, la cliente reçoit un message et note en 1 clic. Taux de réponse × 10 comparé au "tu peux me laisser un avis ?".</p><p class="detail">Notes positives → redirigées vers Google. Notes basses → feedback privé pour vous améliorer sans ternir votre image.</p><div class="fvc-visual"><div style="text-align:center"><span style="color:var(--gold);font-size:20px;letter-spacing:3px">★★★★★</span><p style="font-size:12px;color:#555;margin-top:6px">12 nouveaux avis ce mois</p></div></div></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ig">🧾</div><h4>Factures auto <span class="fvb fvb-a">Auto</span></h4><div class="fvc-pain">😤 "Je fais mes factures à la main, ça me prend un temps fou"</div></div><div class="fvc-body"><p>Après chaque RDV payé, une facture PDF est générée et envoyée automatiquement à la cliente.</p><p class="detail">Parfait pour les clientes en note de frais. Numérotation légale, TVA, coordonnées — tout conforme.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ib">🗓️</div><h4>Prochain RDV auto <span class="fvb fvb-a">Auto</span></h4><div class="fvc-pain">😤 "Mes clientes oublient de revenir, je les perds sans m'en rendre compte"</div></div><div class="fvc-body"><p>À la fin du RDV, suggestion automatique : "Prochain RDV dans X semaines ?". Vous confirmez en 1 clic, la cliente reçoit un email.</p><p class="detail">Le meilleur anti-churn qui existe. Basé sur le cycle naturel de chaque prestation (retouche racines = 6 sem, coupe = 8 sem...).</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ip">📈</div><h4>Objectif CA mensuel</h4><div class="fvc-pain">😤 "Je navigue sans boussole, je sais jamais si le mois est bon"</div></div><div class="fvc-body"><p>Barre de progression permanente dans votre dashboard. Vous voyez en temps réel combien il reste pour atteindre l'objectif.</p><p class="detail">En avance ? Motivation. En retard ? Suggestions d'actions concrètes pour remplir les derniers créneaux.</p><div class="fvc-visual"><div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:6px"><span style="color:var(--muted)">7 820€ / 10 000€</span><span style="font-weight:700;color:var(--green)">78%</span></div><div class="fvbar"><div class="fvbf" style="width:78%;background:var(--green)"></div></div></div></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ir">🔮</div><h4>Prédiction de départ <span class="fvb fvb-ia">IA</span></h4><div class="fvc-pain">😤 "Je découvre qu'une cliente est partie seulement quand c'est trop tard"</div></div><div class="fvc-body"><p>Score 0-100 de risque de perte. L'IA analyse fréquence en baisse, panier qui diminue, pas de rebook.</p><p class="detail">Vous êtes prévenue AVANT que la cliente parte. Un simple message suffit souvent à la faire revenir.</p><div class="fvc-visual"><div class="fvc-visual-mini"><div class="dot" style="background:var(--red)"></div><strong>Sarah M.</strong> — Risque : <strong style="color:var(--red)">82/100</strong></div><p style="font-size:10px;color:var(--muted);margin-top:6px">Pas venue depuis 49 jours</p></div></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ipk">🎯</div><h4>Objectifs gamifiés <span class="fvb fvb-u">Unique</span></h4><div class="fvc-pain">😤 "Je dois faire le flic pour motiver mon équipe, c'est épuisant"</div></div><div class="fvc-body"><p>"Sophie est à 92% — plus que 2 coupes ! 🔥" Badges, classements, célébrations. L'équipe se motive toute seule.</p><p class="detail">Objectifs par coiffeuse (CA, nombre de RDV, rebook), progression visible, notifications quand l'objectif est atteint.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ip">💡</div><h4>Coach proactif <span class="fvb fvb-ia">IA</span></h4><div class="fvc-pain">😤 "J'ai des chiffres partout mais personne ne me dit quoi FAIRE"</div></div><div class="fvc-body"><p>"3 créneaux vides jeudi. Envoie un flash ?" — "Les salons qui communiquent 2×/mois ont 23% de rebook en plus."</p><p class="detail">Un vrai coach business qui analyse vos données et vous pousse à agir. Pas un outil passif que vous oubliez.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ic">🌍</div><h4>Multi-langue auto <span class="fvb fvb-a">Auto</span></h4><div class="fvc-pain">😤 "Mes clientes touristes comprennent rien à ma page de réservation"</div></div><div class="fvc-body"><p>Page de réservation traduite automatiquement selon la langue du navigateur de la cliente.</p><p class="detail">À Paris avec 30% de touristes : indispensable. Anglais, espagnol, arabe, chinois... tout automatique.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ipk">📸</div><h4>Feed social intégré <span class="fvb fvb-u">Unique</span></h4><div class="fvc-pain">😤 "Ma page de réservation est froide, aucune photo, les clientes hésitent"</div></div><div class="fvc-body"><p>Mini Instagram dans votre page de réservation. La cliente scrolle vos réalisations, voit un balayage, clique "Je veux ça".</p><p class="detail">Photos avant/après, galerie par prestation. Transforme votre page en vitrine vivante.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon igo">🤝</div><h4>Mode duo / groupe <span class="fvb fvb-u">Unique</span></h4><div class="fvc-pain">😤 "C'est la galère quand des copines veulent réserver ensemble"</div></div><div class="fvc-body"><p>2 créneaux, 2 coiffeuses, 1 seule réservation. EVJF, mère-fille, entre copines. Personne d'autre ne le fait.</p><p class="detail">La cliente choisit les prestations pour chacune, My Presty trouve les créneaux qui matchent.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ip">🧠</div><h4>Mémoire contextuelle <span class="fvb fvb-ia">IA</span></h4><div class="fvc-pain">😤 "J'oublie toujours les préférences de mes clientes, c'est gênant"</div></div><div class="fvc-body"><p>"Sarah veut un balayage plus froid. Elle aime le thé vert. Son fils s'appelle Lucas." Tout affiché le matin du RDV.</p><p class="detail">Notes automatiques, préférences, allergies, ce qu'elle a dit la dernière fois. Chaque coiffeuse devient concierge de luxe.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ig">🚀</div><h4>Landing page SEO <span class="fvb fvb-a">Auto</span></h4><div class="fvc-pain">😤 "Mon salon est invisible sur Google, je perds des clientes"</div></div><div class="fvc-body"><p>Page web optimisée générée automatiquement. "Coiffeur balayage Paris 11" → votre page apparaît.</p><p class="detail">SEO local, mots-clés par prestation, avis intégrés, schema markup. Sans rien toucher.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ib">⏰</div><h4>Rappels intelligents <span class="fvb fvb-ia">IA</span></h4><div class="fvc-pain">😤 "Mes rappels sont tous les mêmes, personne ne les lit"</div></div><div class="fvc-body"><p>"Ton lissage a 3 semaines. Shampoing sans sulfate recommandé. Retouche ?" Conseil pro adapté + CTA de rebook.</p><p class="detail">Chaque rappel est personnalisé selon la prestation effectuée. Pas un SMS générique mais un vrai conseil professionnel.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ic">📆</div><h4>Vacances intelligentes <span class="fvb fvb-a">Auto</span></h4><div class="fvc-pain">😤 "Quand je suis en vacances, mes clientes voient 'indisponible' et partent"</div></div><div class="fvc-body"><p>Sophie en vacances ? Ses clientes sont automatiquement redirigées vers Marie avec un message personnalisé.</p><p class="detail">Aucune cliente perdue pendant vos congés. Transfert transparent, la cliente ne voit même pas la différence.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon igo">📉</div><h4>Courbe de fidélité</h4><div class="fvc-pain">😤 "Je découvre qu'une cliente a disparu seulement après des mois"</div></div><div class="fvc-body"><p>Graphique par cliente : fréquence, panier moyen, prestations. Une courbe qui descend vous alerte immédiatement.</p><p class="detail">Visualisez l'évolution de chaque relation client. Agissez au premier signe de désengagement.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon igo">🎁</div><h4>Programme VIP <span class="fvb fvb-u">Unique</span></h4><div class="fvc-pain">😤 "Mes cartes de fidélité se perdent, c'est nul"</div></div><div class="fvc-body"><p>Bronze, Argent, Or, Diamant. Basé sur les dépenses réelles. Avantages automatiques à chaque niveau.</p><p class="detail">Priorité de réservation VIP, soin offert anniversaire, remises exclusives. La cliente voit son statut sur la page de réservation.</p><div class="fvc-visual"><div style="display:flex;gap:3px;font-size:9px;text-align:center;letter-spacing:.5px;text-transform:uppercase;font-weight:600"><div style="flex:1;padding:8px 4px;background:#F5E6D3;color:#92400E;border-radius:4px">Bronze</div><div style="flex:1;padding:8px 4px;background:#E8E8E4;color:#555;border-radius:4px">Argent</div><div style="flex:1;padding:8px 4px;background:linear-gradient(135deg,#F5E6D3,#C4A265);color:#FFF;border-radius:4px">Or</div><div style="flex:1;padding:8px 4px;background:var(--dark);color:#FFF;border-radius:4px">Diamant</div></div></div></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ir">🔄</div><h4>Historique de prix <span class="fvb fvb-u">Unique</span></h4><div class="fvc-pain">😤 "Je n'ose jamais augmenter mes prix, je sais pas si c'est le bon moment"</div></div><div class="fvc-body"><p>"Pas augmenté depuis 14 mois. Inflation 4.2%. Vous perdez 420€/mois." Bouton +5% en 1 clic.</p><p class="detail">Historique complet de chaque tarif, comparaison avec l'inflation, simulation de l'impact sur votre CA.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ib">🏪</div><h4>Mode multi-salon</h4><div class="fvc-pain">😤 "Je jongle entre 2 comptes séparés, c'est ingérable"</div></div><div class="fvc-body"><p>Dashboard unique, statistiques combinées, switch entre salons en 1 clic. Pour les gérantes qui grandissent.</p><p class="detail">Comparez les performances entre salons, transférez des clientes, gérez les équipes centralement.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ir">🛡️</div><h4>Protection no-show</h4><div class="fvc-pain">😤 "J'ai perdu un créneau de 80€ aujourd'hui, la cliente est pas venue"</div></div><div class="fvc-body"><p>Acompte obligatoire, politique d'annulation automatique, frais de no-show prélevés.</p><p class="detail">Définissez vos règles : acompte de 30%, annulation gratuite 24h avant, frais de 50% en cas de no-show.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ipk">👩‍👧</div><h4>Parrainage intégré</h4><div class="fvc-pain">😤 "Le bouche-à-oreille marche mais je peux pas le mesurer ni le récompenser"</div></div><div class="fvc-body"><p>Code unique par cliente, compteur de filleuls, crédits automatiques pour la marraine et la filleule.</p><p class="detail">La cliente partage son code, la nouvelle cliente l'utilise → les deux reçoivent un crédit automatiquement.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ip">🎰</div><h4>Roue de la chance</h4><div class="fvc-pain">😤 "L'expérience cliente s'arrête au paiement, y'a rien de fun"</div></div><div class="fvc-body"><p>Après chaque paiement, la cliente tourne la roue. -10%, soin offert, produit gratuit. Gamification post-achat.</p><p class="detail">Vous configurez les lots et les probabilités. La cliente revient pour rejouer — c'est addictif.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ig">🧲</div><h4>Cartes cadeau</h4><div class="fvc-pain">😤 "J'ai aucun moyen de vendre des bons cadeaux en ligne"</div></div><div class="fvc-body"><p>Cartes digitales avec code unique, solde restant visible, message personnalisé.</p><p class="detail">Disponible sur votre page publique. Parfait pour Noël, fête des mères, anniversaires. Paiement Stripe direct.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ir">📦</div><h4>Gestion de stock</h4><div class="fvc-pain">😤 "Je suis en rupture de stock en plein rendez-vous, c'est la honte"</div></div><div class="fvc-body"><p>Inventaire, alertes stock bas, suivi des ventes. Olaplex à 3 restants ? Vous le savez avant la rupture.</p><p class="detail">Associez des produits à des prestations, suivez la consommation, recevez des alertes proactives.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon igo">🎫</div><h4>Forfaits & packages</h4><div class="fvc-pain">😤 "Je peux pas proposer de prix groupé pour des prestations combinées"</div></div><div class="fvc-body"><p>"Forfait Mariée" : essai + jour J + retouche. Prix package vs prix unitaire affiché côte à côte.</p><p class="detail">Créez des bundles illimités, affichez l'économie réalisée. Augmentez le panier moyen naturellement.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ic">💬</div><h4>Communication ciblée</h4><div class="fvc-pain">😤 "J'envoie mes SMS un par un, ça prend des heures"</div></div><div class="fvc-body"><p>Messages groupés : promos flash, nouveautés, rappels personnalisés. SMS + email intégrés en 1 clic.</p><p class="detail">Segmentez par statut VIP, dernière visite, prestation préférée. Le bon message, à la bonne personne.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ib">👥</div><h4>Gestion d'équipe</h4><div class="fvc-pain">😤 "Je fais le suivi de mon équipe sur des bouts de papier"</div></div><div class="fvc-body"><p>Commissions automatiques, objectifs mensuels, formules clients par coiffeuse. Tout centralisé.</p><p class="detail">Chaque membre a sa couleur dans le planning, ses stats, ses objectifs. Transparence totale.</p></div></div>

<div class="fvc"><div class="fvc-head"><div class="fvc-icon ig">📋</div><h4>Liste d'attente</h4><div class="fvc-pain">😤 "Mes clientes partent quand c'est plein, je les perds"</div></div><div class="fvc-body"><p>Créneaux pleins ? La cliente s'inscrit en file d'attente. Un créneau se libère → notification automatique.</p><p class="detail">Remplissez chaque annulation en quelques secondes, sans rien faire. Les annulations deviennent des opportunités.</p></div></div>

</div>
<div class="container"><div class="carousel-nav rv"><button onclick="document.getElementById('featCarousel').scrollBy({left:-350,behavior:'smooth'})">←</button><button onclick="document.getElementById('featCarousel').scrollBy({left:350,behavior:'smooth'})">→</button></div></div>
</section>

<!-- ═══ IA ═══ -->
<section class="ai" id="ia"><div class="container"><div class="aig"><div class="rv-l"><p style="font-size:12px;letter-spacing:4px;text-transform:uppercase;color:var(--purple);margin-bottom:16px;font-weight:600">Intelligence artificielle</p><h2 style="font-family:var(--ss);font-size:clamp(34px,4vw,52px);font-weight:300;margin-bottom:20px;line-height:1.15;color:var(--dark)">Les autres applications comptent.<br/>My Presty <em style="font-style:italic;color:var(--purple)">prédit</em>.</h2><div class="aip"><p><strong>Le vrai problème :</strong> Vous avez des dizaines de chiffres dans votre dashboard mais aucun outil ne vous dit <strong>quoi faire</strong>. Vous regardez des statistiques, pas des actions. Résultat : vous perdez des clientes sans comprendre pourquoi.</p></div>
<div class="aic"><div class="aici">🔮</div><div><h4>Prédiction de churn <span class="aib">IA</span></h4><p class="aicpn">Avant : vous découvrez que Sarah est partie. Après : "Elle va partir dans 2 semaines, agis."</p><p>Score 0-100 basé sur fréquence, panier moyen et comportement de chaque cliente.</p></div></div>
<div class="aic"><div class="aici">💡</div><div><h4>Coach proactif <span class="aib">IA</span></h4><p class="aicpn">Avant : vous réagissez. Après : le système vous pousse.</p><p>"3 créneaux vides jeudi. Envoie un flash maintenant ?"</p></div></div>
<div class="aic"><div class="aici">🧠</div><div><h4>Mémoire contextuelle <span class="aib">IA</span></h4><p class="aicpn">Avant : "C'était quoi déjà ?" Après : tout affiché le matin du RDV.</p><p>Préférences, allergies, notes. Concierge de luxe automatique.</p></div></div>
<div class="aic"><div class="aici">⏰</div><div><h4>Rappel personnalisé <span class="aib">IA</span></h4><p class="aicpn">Avant : rappel générique. Après : conseil pro + CTA rebook.</p><p>"Ton lissage a 3 semaines. Shampoing sans sulfate recommandé."</p></div></div>
</div><div class="rv-r">
<!-- Chat conversation mockup -->
<div class="ai-chat" style="margin-bottom:20px">
  <div class="ai-chat-head"><div class="ai-dot"></div><p>Assistante IA My Presty</p></div>
  <div class="ai-chat-body">
    <div class="ai-msg ai-msg-user">J'ai des trous dans mon planning jeudi, qu'est-ce que je peux faire ?</div>
    <div class="ai-msg ai-msg-ai"><div class="ai-label">✨ IA My Presty</div>Tu as 3 créneaux libres jeudi entre 14h et 17h. Je te propose d'envoyer un message flash aux 12 clientes qui n'ont pas de RDV prévu ce mois-ci. Ça a fonctionné la dernière fois — tu as rempli 2 créneaux en 1h.</div>
    <div class="ai-msg ai-msg-user">Et Sarah Martin, elle revient quand ?</div>
    <div class="ai-msg ai-msg-ai"><div class="ai-label">✨ IA My Presty</div>⚠️ Sarah n'est pas venue depuis 49 jours. Son score de risque est à 82/100. Elle fait habituellement un balayage toutes les 6 semaines. Je te recommande de lui envoyer un message personnalisé aujourd'hui.</div>
  </div>
</div>
<!-- AI proactive tips -->
<div class="ai-chat">
  <div class="ai-chat-head"><div class="ai-dot"></div><p>Conseils proactifs</p></div>
  <div class="ai-chat-body">
    <div class="ai-msg-tip">💡 <strong>Conseil du jour :</strong> Tu n'as pas augmenté tes prix depuis 14 mois. L'inflation est à 4.2%. Tu perds environ 420€/mois. Augmente de 5% maintenant ?</div>
    <div class="ai-msg-tip">🎉 <strong>Bonne nouvelle :</strong> Sophie a atteint son objectif mensuel ! Taux de rebook 94% — le meilleur de l'équipe.</div>
    <div class="ai-msg-tip">📊 <strong>Ton CA :</strong> Tu es à 78% de ton objectif avec encore 8 jours. Remplis 3 créneaux et tu le dépasses.</div>
  </div>
</div>
</div></div></div></section>

<!-- ═══ COMPARE ═══ -->
<section class="compare"><div class="container"><div class="sh rv"><p class="tag">Pourquoi My Presty</p><h2>Ce que My Presty fait différemment</h2></div><div class="cbox rv"><div class="cmp"><p class="name">My Presty</p><p class="desc">42 fonctionnalités · 19€/mois · 0% commission · IA prédictive</p></div><div class="coth"><p class="name">Les autres applications</p><p class="desc">Commission sur chaque réservation ou transaction — plus vous réussissez, plus vous payez</p></div><div class="cmsg"><p><strong>Avec My Presty, c'est un prix fixe.</strong> Toutes les fonctionnalités incluses. Vous gardez 100% de votre chiffre d'affaires.</p><p style="margin-top:16px">Et les fonctionnalités que <strong>personne ne propose</strong> — score de santé, prédiction de churn, mémoire contextuelle, objectifs gamifiés, mode duo, QR code trackable, programme VIP automatique — on les a inventées.</p></div></div></div></section>

<!-- ═══ ONBOARDING ═══ -->
<section class="onboard"><div class="container"><div class="sh rv"><p class="tag">Démarrage</p><h2>Votre salon en ligne en 10 minutes</h2><p>Pas de dashboard vide. On vous guide de A à Z.</p></div><div class="obc rv"><div class="obp" id="obP"><div class="obpf" id="obF" style="width:0%"></div><div class="obdw active" data-step="0"><div class="obd active">1</div><p class="obdl">Salon</p></div><div class="obdw" data-step="1"><div class="obd">2</div><p class="obdl">Prestations</p></div><div class="obdw" data-step="2"><div class="obd">3</div><p class="obdl">Équipe</p></div><div class="obdw" data-step="3"><div class="obd">4</div><p class="obdl">Clientes</p></div><div class="obdw" data-step="4"><div class="obd">5</div><p class="obdl">Style</p></div><div class="obdw" data-step="5"><div class="obd">6</div><p class="obdl">Paiement</p></div><div class="obdw" data-step="6"><div class="obd">7</div><p class="obdl">Partage</p></div></div><div class="obs" id="obS"><div class="obsi" id="obC"></div></div><div class="obn"><button class="obpb" id="obPB" onclick="obGo(-1)">← Précédent</button><span class="obcnt" id="obCnt">1 / 7</span><button class="obnb" id="obNB" onclick="obGo(1)">Suivant →</button></div></div></div></section>

<!-- ═══ TESTIMONIALS ═══ -->
<section><div class="container"><div class="sh rv"><p class="tag">Témoignages</p><h2>Elles ont adopté My Presty</h2></div><div class="tg"><div class="tc rv-s"><div class="stars">★★★★★</div><blockquote>"J'ai remplacé mon agenda, ma caisse et mes rappels. Tout est dans My Presty."</blockquote><p class="author">Sarah K. — Coiffure, Paris 11e</p></div><div class="tc rv-s"><div class="stars">★★★★★</div><blockquote>"Le score de santé m'a ouvert les yeux. 8 clientes en danger, 6 sont revenues."</blockquote><p class="author">Amira D. — Institut, Lyon</p></div><div class="tc rv-s"><div class="stars">★★★★★</div><blockquote>"Mes clientes Diamant se sentent spéciales. Les nouvelles veulent monter de niveau."</blockquote><p class="author">Julie M. — Nail bar, Bordeaux</p></div></div></div></section>

<!-- ═══ PRICING ═══ -->
<section class="pricing" id="tarifs"><div class="container"><div class="sh rv"><p class="tag">Tarifs</p><h2>Simple, transparent, sans commission</h2><p>Un prix fixe, tout inclus.</p></div><div class="pgr"><div class="pcd rv-s"><p class="tier">Découverte</p><h3>Essai gratuit</h3><div class="price">0€ <span>/ 90 jours</span></div><p class="billing">Sans carte bancaire</p><ul><li>Toutes les fonctionnalités</li><li>50 RDV / mois</li><li>Page de réservation</li><li>Support email</li></ul><a href="#essai" class="btn btn-o" style="width:100%;text-align:center;padding:14px">Commencer gratuitement</a></div><div class="pcd ft rv-s"><p class="tier">Pro</p><h3>Tout inclus</h3><div class="price">19€ <span>/ mois</span></div><p class="billing">Sans engagement</p><ul><li>RDV illimités</li><li>Caisse + exports</li><li>IA + score de santé</li><li>VIP + fidélité</li><li>QR Code + avis auto</li><li>Rapports PDF</li><li>Support prioritaire</li></ul><a href="#essai" class="btn" style="width:100%;text-align:center;padding:14px;background:#FFF;color:var(--dark)">Essayer 90 jours gratuit</a></div><div class="pcd rv-s"><p class="tier">Multi-salon</p><h3>Pour les groupes</h3><div class="price">49€ <span>/ mois</span></div><p class="billing">Par salon supplémentaire</p><ul><li>Tout le plan Pro</li><li>Dashboard multi-salon</li><li>Stats consolidées</li><li>Account manager</li></ul><a href="#essai" class="btn btn-o" style="width:100%;text-align:center;padding:14px">Nous contacter</a></div></div></div></section>

<!-- ═══ FINAL CTA ═══ -->
<section class="fcta" id="essai"><h2 class="rv">Prête à transformer<br/>votre salon en <em>machine</em> ?</h2><p class="rv">90 jours gratuits. Toutes les fonctionnalités. Sans carte bancaire.</p><div class="rv"><a href="/inscription" class="btn btn-d btn-big">Créer mon salon maintenant</a><p class="trial">Rejoignez les salons qui ne gèrent plus — ils pilotent.</p></div></section>

<footer><div class="container"><div class="fi"><div class="fb">MY PRESTY</div><div class="flinks"><a href="#fonctionnalites">Fonctionnalités</a><a href="#tarifs">Tarifs</a><a href="#">Contact</a></div><p class="fc">© 2025 My Presty — Tous droits réservés</p></div></div></footer>

<button class="btt" id="btt" onclick="window.scrollTo({top:0,behavior:'smooth'})" aria-label="Retour en haut">↑</button>
<div class="flcta" id="flcta"><a href="#essai">✦ Essai gratuit 90 jours</a></div>

    `}} />
  </>);
}
